name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: docker login
      env: 
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      
#    - name: remove old image
#      run: docker rmi -f the-diary-repo:latest
      
    - uses: actions/checkout@v3
    
    - name: Build the Docker image
      run: docker build -t chatbot:latest .
      
    - name: docker tag
      run: docker tag chatbot:latest jaisivram/mybharathi-chatbot

    - name: docker push 
      run: docker push jaisivram/mybharathi-chatbot
